# Generated by Django 2.2.17 on 2020-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='corrected_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
